package ServerObjectInterfaceApp;


/**
* ServerObjectInterfaceApp/ServerObjectInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerObjectInterface.idl
* Thursday, February 29, 2024 4:16:03 o'clock PM EST
*/

public interface ServerObjectInterface extends ServerObjectInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerObjectInterface
